### ISSUE TITLE
Open Graph Tags

### ISSUE THREAD

**Issue by nltncsr** [indacode/wordpress_blog#10]
We have to optimize Open Graph tags so we can share our posts and look right in social networks.

**Comment by nltncsr** [comment]
Done!
The main Open Graph tags like `og:title`, `og:descrition` and `og:image` were added to `header.php` in the main theme, correctly adjusted if the open page is the index or is a post.

**Comment by mazulo** [comment]
AAAH! THAT DELICIOUS, DUDE!
